# اسم الـ Action الذي سيظهر في حسابك
name: Build Android APK

# هذا يحدد متى يتم تشغيل الـ Action
on:
  # 1. التشغيل عند أي عملية push على الفرع main
  push:
    branches:
      - main
      - master # (إذا كان اسم الفرع الرئيسي عندك master)
      
  # 2. السماح بالتشغيل اليدوي من داخل صفحة Actions في GitHub
  workflow_dispatch:

jobs:
  build-apk:
    # سيتم استخدام خادم Ubuntu الأحدث لبناء التطبيق
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: سحب الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v4

      # الخطوة 2: تثبيت الجافا (JDK)، وهي ضرورية لبناء تطبيقات أندرويد
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # الخطوة 3: تثبيت Flutter بالإصدار المحدد
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
          cache: true

      # الخطوة 4: تنظيف المشروع (مهم جداً)
      - name: Clean project
        run: flutter clean

      # الخطوة 5: تثبيت الاعتماديات (Packages)
      - name: Install dependencies
        run: flutter pub get

      # الخطوة 6: إصلاح مشكلة namespace للمكتبات القديمة
      - name: Fix namespace issues in dependencies
        run: |
          # البحث عن جميع ملفات build.gradle التي تحتاج namespace
          for plugin in flutter_keyboard_visibility file_picker flutter_plugin_android_lifecycle path_provider_android permission_handler_android printing share_plus sqflite_android; do
            BUILD_FILE=$(find $HOME/.pub-cache/hosted/pub.dev -name "build.gradle" -path "*/$plugin*/android/*" 2>/dev/null | head -n 1)
            if [ -f "$BUILD_FILE" ] && ! grep -q "namespace" "$BUILD_FILE"; then
              echo "Adding namespace to $plugin..."
              PACKAGE_NAME=$(echo $plugin | sed 's/_/./g')
              sed -i "/android {/a \    namespace 'com.$PACKAGE_NAME'" "$BUILD_FILE"
            fi
          done

      # الخطوة 8: بناء ملف الـ APK (النسخة النهائية Release)
      - name: Build APK
        run: flutter build apk --release

      # الخطوة 9: رفع ملف الـ APK الناتج كـ "Artifact"
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
